import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { List } from '@mantine/core';
import todolist from '../assets/todolist-image.png'
import { Task } from '@/components/Task';
import { AddTaskBar } from '@/components/AddTaskBar';
import type { Task as ITask } from '../types/todolist'
import { searchTask } from '../services/searchToDoList'
import { useState, useEffect } from 'react';
import { FilterTask } from '@/components/FilterTask';


export default function Home() {
  const [tasks, setTasks] = useState<ITask[]>([])

  useEffect(() => {
    searchTask()
    .then(res => setTasks(res?.content))
  },[])

  return (
    <>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles['main']}>
        <section>
          <Image
            src={todolist}
            alt='todolist'
          />
          <AddTaskBar setTasks={setTasks} />
          <FilterTask setTasks={setTasks}  />
          <List
            w={'100%'}
            spacing="lg"
            size="sm"
            center
          >
            {tasks?.map((task) => <Task key={task.id} {...task} setTasks={setTasks} />)}
          </List>
        </section>
      </main>
    </>
  )
}
