version: '3'

services:
  app:
    container_name: frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_URL: http://localhost:8080
        NEXT_PUBLIC_URL_SSR: http://server:8080
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - todolist_network
networks:
  todolist_network:
    external: true