version: '3.8'

services:
  app:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_URL: http://localhost:8080
    restart: always
    ports:
      - "3000:3000"
    networks:
      - todolist_network
networks:
  todolist_network:
    external: true